include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_private_typedef_functions: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    await_only_futures: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    library_prefixes: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_closures: true
    package_api_docs: true
    package_names: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_generic_function_type_aliases: true
    prefer_initializing_formals: true
    prefer_is_not_empty: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    secure_pubspec_urls: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_overrides: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    valid_regexps: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_setters_without_getters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    cascade_invocations: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    file_names: true
    invariant_booleans: true
    library_names: true
    literal_only_boolean_expressions: true
    no_default_cases: true
    only_throw_errors: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_const_constructors: true
    prefer_final_in_for_each: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_iterable_whereType: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_statements: true
    use_colored_box: true
    use_decorated_box: true
    use_is_even_rather_than_modulo: true